project:
  type: website

website:
  title: "JJL's Matplotlib blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leejjoon/jjl-mpl-blog
format:
  html:
    theme: cosmo
    css: styles.css



